### ISSUE TITLE
Responsividade em Minhas Tecnologias

### ISSUE THREAD

**Issue by vitorsouzaalmeida** [rodrigonahid/portfolio#1]
Há um erro de responsividade relativamente simples de resolver.
Ele continua do lado uma da outra mesmo estando em mobile, sendo que deveria ficar uma em baixo da outra.
![image](https://user-images.githubusercontent.com/70543018/135715572-b53bab9e-daf6-4f5a-b567-d883a9c871b4.png)

**Comment by rodrigonahid** [comment]
Fala Laks, obrigado pelo feedback! Isso na verdade é um scroll horizontal, mas não ficou claro, vou arrumar outra solução, talvez um carousel. Abraços!

**Comment by rodrigonahid** [comment]
> Há um erro de responsividade relativamente simples de resolver.
> Ele continua do lado uma da outra mesmo estando em mobile, sendo que deveria ficar uma em baixo da outra.
> ![image](https://user-images.githubusercontent.com/70543018/135715572-b53bab9e-daf6-4f5a-b567-d883a9c871b4.png)

Fala Vitor, obrigado pelo feedback! Isso na verdade é um scroll horizontal, mas não ficou claro, vou arrumar outra solução, talvez um carousel. Abraços!

**Comment by vitorsouzaalmeida** [comment]
A ideia do scroll horizontal é boa. Acho que faltou um feedback visual sobre ele, poderia existir uma barra mostrando que tem algo ao lado ou uma seta que seja clicavel, e depois do segundo item para frente ela some. Abraços
